[build]
  # The directory to change to before starting a build.
  # This is where your package.json with the 'build' script lives.
  base = "ikmal-page"

  # The command to run to build your site
  command = "npm run build"

  # The directory that contains the deploy-ready HTML files and assets
  # (Relative to the base directory)
  publish = "out"
